### ISSUE TITLE
Edit Page does not work if text effects have quotes in them

### ISSUE THREAD

**Issue by nagoshiashumari** [idmontie/ChibiCritters#1]
For example, if a card's effect is:

```
If a "Drizzle Dynasty" Critter on your side of the field would be destroyed that is not this card, you can detach one Love from this card. That Critter is not destroyed.
```

The edit page fails to populate the text field. And if you go to the console, you get the following error:

```
Uncaught SyntaxError: Unexpected identifier 
```

[Here's a link to a page that fails](http://www.chibicritters.com/admin/card-maker/cards/edit/46)

**Comment by idmontie** [comment]
See this solution: http://stackoverflow.com/a/169035/759316

Apply it to this file: https://github.com/idmontie/ChibiCritters/blob/master/admin/app/views/card-maker/_form.html.php
