### ISSUE TITLE
Install Bootsrap

### ISSUE THREAD

**Issue by nagoshiashumari** [idmontie/ChibiCritters#10]
We don't have Bootstrap installed, and we should. The gallery could use the tables feature.

**Comment by idmontie** [comment]
Bootstrap is already in the theme.  It is just not being utilized.https://github.com/idmontie/ChibiCritters/blob/master/wordpress/wp-content/themes/chibicritters/functions.php#L182

You should be able to use bootstrap classes in your Posts and Pages.
