### ISSUE TITLE
Need to remove 'powered by wordpress' in the footer

### ISSUE THREAD

**Issue by nagoshiashumari** [idmontie/ChibiCritters#8]
The footer currently contains a part that says "powered by wordpress". This should be removed.

**Comment by idmontie** [comment]
Remove `<a href="<?php echo esc_url( __( 'http://wordpress.org/', 'chibicritters' ) ); ?>" title="<?php esc_attr_e( 'Semantic Personal Publishing Platform', 'chibicritters' ); ?>"><?php printf( __( 'Proudly powered by %s', 'chibicritters' ), 'WordPress' ); ?></a>` from https://github.com/idmontie/ChibiCritters/blob/master/wordpress/wp-content/themes/chibicritters/footer.php#L19.

**Comment by nagoshiashumari** [comment]
Done and done. Thank you!
