### ISSUE TITLE
The site is to narrow

### ISSUE THREAD

**Issue by nagoshiashumari** [idmontie/ChibiCritters#9]
(Except on the front page) We're only using about a third of the screen. We need to widen that.

**Comment by idmontie** [comment]
Change `class="col-md-6 col-md-offset-3"` to `class="col-md-10 col-md-offset-1"` in https://github.com/idmontie/ChibiCritters/blob/4d5c90c3b4c4dcb8ffc4224ac9fc9a178dc4e86e/wordpress/wp-content/themes/chibicritters/content.php#L14.

That **should** be the only file that needs changing.

**Comment by nagoshiashumari** [comment]
Yeah I changed it on the blog post section. I'll get to the rest of the site soon.
